# https://docs.github.com/ja/free-pro-team@latest/actions

name: Test

on: [push, pull_request]

jobs:
  validate-dependencies:
    name: Validate dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Using Composer version 2
        run: sudo composer self-update --2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer Directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

  validate-schema:
    name: Validate schema
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Using Composer version 2
        run: sudo composer self-update --2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer Directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint ruleset.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./src/Blue32a/ruleset.xml
          xml-schema-file: ./vendor/squizlabs/php_codesniffer/phpcs.xsd
